export const galleryImages = [
  {
    id: 1,
    src: "/images/banner1.jpg",
    size: "tall",
    cat: "Campus",
    // title: "Main Faculty Wing",
  },
  {
    id: 2,
    src: "/images/sports.jpg",
    size: "wide",
    cat: "Sports",
    title: "Football",
  },
  {
    id: 3,
    src: "/images/sciencelab2.jpg",
    size: "square",
    cat: "Innovation Labs",
    title: "Innovation Lab",
  },
  {
    id: 4,
    src: "/images/events.webp",
    size: "square",
    cat: "Events",
    title: "Cultural Fest",
  },
  {
    id: 5,
    src: "/images/banner3.jpg",
    size: "tall",
    cat: "Campus",
    title: "Bus Facilities",
  },
  {
    id: 6,
    src: "/images/library.jpg",
    size: "wide",
    cat: "Academics",
    title: "Library",
  },
  {
    id: 7,
    src: "/images/banner8.jpg",
    size: "square",
    cat: "Sports",
    title: "Basketball Championship",
  },
  {
    id: 8,
    src: "/images/growth.jpg",
    size: "square",
    cat: "Sports",
    title: "Indoor Games",
  },
  {
    id: 9,
    src: "/images/computerlab.jpg",
    size: "square",
    cat: "Innovation Labs",
    title: "Computer Lab",
  },
  {
    id: 10,
    src: "/images/banner7.jpg",
    size: "square",
    cat: "Innovation Labs",
    title: "Computer Lab",
  },
  {
    id: 11,
    src: "/images/games.jpg",
    size: "square",
    cat: "Sports",
    title: "Indoor Games",
  },
  {
    id: 12,
    src: "/images/sciencelab.png",
    size: "square",
    cat: "Innovation Labs",
    title: "Science Lab",
  },
  {
    id: 13,
    src: "/images/cocurricular.jpg",
    size: "square",
    cat: "Academics",
    title: "Class Activities",
  },
  {
    id: 14,
    src: "/images/classroom.jpg",
    size: "square",
    cat: "Academics",
    title: "Class Rooms",
  },
  {
    id: 15,
    src: "/images/smartclassroms.jpg",
    size: "square",
    cat: "Academics",
    title: "Smart Class Rooms",
  },
  {
    id: 16,
    src: "/images/banner2.jpg",
    size: "square",
    cat: "Campus",
    // title: "Main Faculty Wing",
  },

  {
    id: 17,
    src: "/images/banner4.jpg",
    size: "square",
    cat: "Campus",
    // title: "Main Faculty Wing",
  },
  {
    id: 18,
    src: "/images/banner5.jpg",
    size: "square",
    cat: "Campus",
    // title: "Main Faculty Wing",
  },
  {
    id: 19,
    src: "/images/campus.jpg",
    size: "square",
    cat: "Campus",
    // title: "Main Faculty Wing",
  },
  {
    id: 20,
    src: "/images/campus2.jpg",
    size: "square",
    cat: "Campus",
    // title: "Main Faculty Wing",/
  },
];

export const footerImages = [
  "/images/banner1.jpg",
  "/images/banner3.jpg",
  "/images/library.jpg",
  "/images/sports.jpg",
  "/images/events.webp",
  "/images/sciencelab2.jpg",
];

export const categories = [
  "All",
  "Campus",
  "Academics",
  "Sports",
  "Events",
  "Innovation Labs",
];
